### PR TITLE
Basic dockerization

### PR DESCRIPTION
**Pull request by DeanAyalon**
This application is rather simple to containerize, so I went ahead and done it, as per issue #3 

The image is not necessarily slim, and can probably be reduced, but it suits the project's needs

# Current configuration
## Dockerfile
- The docker image used is node:19-bullseye
- it copies the repository files into `/app` and installs the dependencies into the image
- The entrypoint is set to `npm run`
- The default command is `dev`, resulting in `npm run dev`

> Once you build the image and push it to Docker Hub, users will not have to build the image or even clone the repository, just pull it from your repository!

## Docker Compose
When using Docker Compose, I have separated the app into three alternate services:
- **base**: The base service contains the image and build instructions to run the app
  > The image is currently called `ghcr.io/deanayalon/free-admin-dashboard-fork`, see [image name](#image-name)
- **standalone**: Maps port 5173 to the host machine, if not used with a proxy - Not secure, but valid for local use
- **dev**: Mounts the project's files into the container, to reflect changes in real time, for simpler development

### Use
```sh
docker compose up -d standalone # Run the app locally
docker compose up -d dev        # Run the app in development mode (project mount)
```
> When using a reverse-proxy, simply use the `base` service. 

## Image Name
The image is currently named `ghcr.io/deanayalon/free-admin-dashboard-fork`, it is pushed to my GitHub account. You can pull it and use the app immediately without ever cloning the repository by doing:
```sh
docker run -p 5173:5173 ghcr.io/deanayalon/free-admin-dashboard-fork
```

**You can use `ghcr.io/Kuzma02/Free-Admin-Dashboard` as the image name, and it will autoamtically be linked with your GitHub repository!**

## Package.json
Modified `npm run dev` to execute `vite --host 0.0.0.0`, so the container listens on all addresses

### CODE REVIEW

**Review by Kuzma02 — CHANGES_REQUESTED** [review]
Hi Dean,

Thank you for your contribution. Before merging I would like you to leave the React application starting with Vite and have the "npm run dev:docker" command for running a containerized version. I have modified a package.json file so you will better understand what I want. After these changes, I will merge everything.

**Comment by DeanAyalon** [comment]
I updated the image's default command to be `dev:docker`

Alternatively, the package.json does not necessarily require dev:docker to be defined, as the command can be changed to `npm run dev -- --host 0.0.0.0` instead

This can be done using `CMD ["dev", "--", "--host", "0.0.0.0"]` in the dockerfile

**Review by Kuzma02 — APPROVED** [review]

**Comment by DeanAyalon** [comment]
The compose file you have merged still uses `ghcr.io/deanayalon/free-admin-dashboard-fork` as the image

```yml
services: 
  base:
    image: ghcr.io/Kuzma02/Free-Admin-Dashboard
```

This should probably be changed to `ghcr.io/Kuzma02/Free-Admin-Dashboard` so that it can be updated and controlled in your repository, rather than mine

Besides installing Docker, to update the image in the future, all you need to do is 
```sh
docker compose build base # Rebuild the image with the new files
docker compose push base  # Pushes the image to GitHub Container Registry
```

To be able to push it, you'll need to authenticate your Docker CLI tool with ghcr.io (For which you will need to create a Personal Access Token)
```sh
docker login ghcr.io
```

I will not be updating the image myself as you continue developing this dashboard

You could also create a GitHub Action that automatically updates the image when a new commit is pushed to this repository

**Comment by Kuzma02** [comment]
Thank you, Dean.

**Pull request merged**
